sudo: false
language: python
python:
 - "3.3"
 - "3.4"
 - "3.5"
 - "3.6"
env:
  matrix:
   - DJANGO="Django<1.10"
   - DJANGO="Django<1.11"
   - DJANGO="Django==1.11b1"
install:
 - travis_retry pip install -r requirements.txt
