sudo: true
language: python
python:
  - "3.6"
env:
  matrix:
    - DJANGO="Django<1.10"
    - DJANGO="Django<1.11"
    - DJANGO="Django==1.11b1"
install:
  - travis_retry pip install -r requirements.txt
  - npm config set prefix /usr/local
  - npm install bower
script:
  - python manage.py bower install
  - python manage.py collectstatic
  - python manage.py makemigrations
  - python manage.py migrate
