sudo: required
language: python
services:
  - docker
python:
  - "3.6"
env:
  matrix:
    - DJANGO="Django<1.10"
    - DJANGO="Django<1.11"
    - DJANGO="Django==1.11b1"
script:
  - docker-compose build
