sudo: required
language: python
services:
  - docker
python:
  - "3.6"
env:
  DOCKER_COMPOSE_VERSION: 1.11.2
  matrix:
    - DJANGO="Django<1.10"
    - DJANGO="Django<1.11"
    - DJANGO="Django==1.11b1"
before_install:
  - docker-compose --version
  - docker-compose pull
  - docker-compose build
  - docker-compose start
  - docker ps
